version: "3.9" #docker version

services:
  web:
    build: .
    command: gunicorn material_project.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=development
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/PostgreSQL/data
    environment:
      - POSTGRES_DB=material_hopper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asd123asd
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
volumes:
  postgres_data:



