# Generated by Django 4.0.3 on 2022-06-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Customer')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=25, null=True, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='PullingProduct',
            fields=[
                ('part_id_customer', models.CharField(max_length=20, verbose_name='Part ID Customer')),
                ('part_id_sanwa', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Part ID Internal')),
                ('part_name', models.CharField(max_length=255, verbose_name='Part Name')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('rack', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rack')),
                ('bin_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bin Quantity')),
                ('packaging_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Packaging Quantity')),
                ('full_bin_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Full Bin Quantity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulling.pullingcustomer', verbose_name='Customer')),
            ],
        ),
    ]
