# Generated by Django 4.0.3 on 2022-07-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishGoodStock',
            fields=[
                ('part_id_customer', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Part ID Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('total_quantity', models.IntegerField(blank=True, default=0, verbose_name='Total Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='PullingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Customer')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=25, null=True, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='PullingFinishGoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref No.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date / Time')),
            ],
        ),
        migrations.CreateModel(
            name='ScanInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('line', models.CharField(blank=True, max_length=255, null=True, verbose_name='No Mc')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref No.')),
                ('rack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='ScanOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('requirement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requirement')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('no_of_bin', models.IntegerField(blank=True, null=True, verbose_name='No of bin')),
                ('spq', models.CharField(blank=True, max_length=255, null=True, verbose_name='SPQ')),
                ('rack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='TempPullingScanInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('line', models.CharField(blank=True, max_length=255, null=True, verbose_name='No Mc')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref No.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='TempPullingScanOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('requirement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requirement')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('no_of_bin', models.IntegerField(blank=True, null=True, verbose_name='No of bin')),
                ('spq', models.CharField(blank=True, max_length=255, null=True, verbose_name='SPQ')),
                ('rack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rack')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='PullingProduct',
            fields=[
                ('part_id_customer', models.CharField(max_length=20, verbose_name='Part ID Customer')),
                ('part_id_sanwa', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Part ID Internal')),
                ('part_name', models.CharField(max_length=255, verbose_name='Part Name')),
                ('material', models.CharField(max_length=255, verbose_name='Material')),
                ('rack', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rack')),
                ('bin_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bin Quantity')),
                ('packaging_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Packaging Quantity')),
                ('full_bin_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Full Bin Quantity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulling.pullingcustomer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PullingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Production Date')),
                ('pulling_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulling.pullingproduct')),
            ],
        ),
    ]
