# Generated by Django 4.0.3 on 2022-06-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Production Date')),
                ('tooling', models.CharField(max_length=3, verbose_name='#Tooling')),
                ('shift_group', models.CharField(max_length=2, verbose_name='Shift - Group')),
                ('line', models.CharField(max_length=3, verbose_name='Line')),
                ('remarks', models.CharField(max_length=255, verbose_name='Remarks')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulling.pullingproduct')),
            ],
        ),
    ]
