# Generated by Django 4.0.3 on 2022-06-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0002_pullinglabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullinglabel',
            old_name='product',
            new_name='pulling_product',
        ),
        migrations.AlterField(
            model_name='pullinglabel',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks'),
        ),
    ]
