# Generated by Django 4.0.3 on 2022-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0003_rename_product_pullinglabel_pulling_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullinglabel',
            name='line',
            field=models.CharField(max_length=25, verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='pullinglabel',
            name='shift_group',
            field=models.CharField(max_length=20, verbose_name='Shift - Group'),
        ),
        migrations.AlterField(
            model_name='pullinglabel',
            name='tooling',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='#Tooling'),
        ),
    ]
