# Generated by Django 4.0.3 on 2022-06-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0007_pullingfinishgooditem_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishGoodStock',
            fields=[
                ('part_id_customer', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Part ID Customer')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('total_quantity', models.IntegerField(blank=True, default=0, verbose_name='Total Quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='pullingfinishgooditem',
            name='total_quantity',
        ),
    ]
