# Generated by Django 4.0.3 on 2022-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0008_finishgoodstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPullingScanInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('no_mesin', models.CharField(blank=True, max_length=255, null=True, verbose_name='No Mc')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref No.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='TempPullingScanOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('no_mesin', models.CharField(blank=True, max_length=255, null=True, verbose_name='No Mc')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref No.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
    ]
