# Generated by Django 4.0.3 on 2022-06-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0009_temppullingscaninmodel_temppullingscanoutmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temppullingscaninmodel',
            old_name='no_mesin',
            new_name='line',
        ),
        migrations.RenameField(
            model_name='temppullingscanoutmodel',
            old_name='no_mesin',
            new_name='line',
        ),
        migrations.AlterField(
            model_name='pullingfinishgooditem',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date / Time'),
        ),
    ]
