# Generated by Django 4.0.3 on 2022-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0010_rename_no_mesin_temppullingscaninmodel_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishgoodstock',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name'),
        ),
        migrations.AddField(
            model_name='pullingfinishgooditem',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name'),
        ),
    ]
