# Generated by Django 4.0.3 on 2022-06-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0011_finishgoodstock_part_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('line', models.CharField(blank=True, max_length=255, null=True, verbose_name='No Mc')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ref No.')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='ScanOutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id_customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part ID Customer')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer')),
                ('part_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Part Name')),
                ('lot_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lot No.')),
                ('requirement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Requirement')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('spq', models.CharField(blank=True, max_length=255, null=True, verbose_name='SPQ')),
                ('rack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rack')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date/Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='temppullingscanoutmodel',
            name='line',
        ),
        migrations.RemoveField(
            model_name='temppullingscanoutmodel',
            name='ref_no',
        ),
        migrations.AddField(
            model_name='temppullingscanoutmodel',
            name='rack',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rack'),
        ),
        migrations.AddField(
            model_name='temppullingscanoutmodel',
            name='requirement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Requirement'),
        ),
        migrations.AddField(
            model_name='temppullingscanoutmodel',
            name='spq',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SPQ'),
        ),
    ]
