# Generated by Django 4.0.3 on 2022-07-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0013_scanoutmodel_no_of_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaninmodel',
            name='rack',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
