# Generated by Django 4.0.3 on 2022-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0014_scaninmodel_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanoutmodel',
            name='rack',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
    ]
