# Generated by Django 4.0.3 on 2022-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulling', '0016_scaninmodel_pic_scanoutmodel_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temppullingscaninmodel',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC'),
        ),
        migrations.AlterField(
            model_name='temppullingscanoutmodel',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC'),
        ),
    ]
