# Generated by Django 4.0.3 on 2022-06-09 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=20, verbose_name='Part ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='Part Name')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('cycle_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cycle Time')),
                ('customer', models.CharField(max_length=25, verbose_name='Customer')),
                ('part_weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Part Weight')),
                ('runner_weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Runner Weight')),
                ('cavity', models.PositiveIntegerField(verbose_name='Cavity')),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('shift', models.CharField(max_length=7, verbose_name='Shift')),
                ('jumlah_purge', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Purging')),
                ('jumlah_ng', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Part Scrap')),
                ('jumlah_runner', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Runner')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='PIC')),
            ],
        ),
        migrations.CreateModel(
            name='HopperFillData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_mesin', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15'), ('A16', 'A16'), ('A17', 'A17'), ('A18', 'A18'), ('A19', 'A19'), ('A20', 'A20'), ('A21', 'A21'), ('A22', 'A22'), ('A23', 'A23'), ('A24', 'A24'), ('A25', 'A25'), ('A26', 'A26'), ('A27', 'A27'), ('A28', 'A28'), ('A29', 'A29'), ('A30', 'A30'), ('A31', 'A31'), ('A32', 'A32'), ('A33', 'A33'), ('A34', 'A34'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('B7', 'B7'), ('B8', 'B8'), ('B9', 'B9'), ('B10', 'B10'), ('B11', 'B11'), ('B12', 'B12'), ('B13', 'B13'), ('B14', 'B14'), ('B15', 'B15'), ('B16', 'B16'), ('B17', 'B17'), ('B18', 'B18'), ('B19', 'B19'), ('B20', 'B20'), ('B21', 'B21'), ('B22', 'B22'), ('B23', 'B23'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('C7', 'C7'), ('C8', 'C8'), ('C9', 'C9'), ('C10', 'C10'), ('C11', 'C11'), ('C12', 'C12'), ('C13', 'C13'), ('C14', 'C14'), ('C15', 'C15'), ('C16', 'C16'), ('C17', 'C17'), ('C18', 'C18'), ('C19', 'C19'), ('C20', 'C20'), ('C21', 'C21'), ('C22', 'C22'), ('C23', 'C23'), ('C24', 'C24'), ('C25', 'C25'), ('C26', 'C26'), ('C27', 'C27'), ('C28', 'C28'), ('C29', 'C29'), ('C30', 'C30'), ('C31', 'C31'), ('C32', 'C32'), ('C33', 'C33'), ('C34', 'C34'), ('C35', 'C35'), ('C36', 'C36'), ('C37', 'C37'), ('C38', 'C38'), ('C39', 'C39'), ('C40', 'C40'), ('C41', 'C41'), ('C42', 'C42'), ('C43', 'C43')], max_length=3, verbose_name='No Mesin')),
                ('no_lot', models.IntegerField(blank=True, null=True, verbose_name='No Lot')),
                ('temp', models.IntegerField(verbose_name='Temperature')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jam_isi', models.TimeField(verbose_name='Jam Isi')),
                ('co_virgin', models.PositiveIntegerField(default=0, verbose_name='CO Virgin')),
                ('co_regrind', models.PositiveIntegerField(default=0, verbose_name='CO Regrind')),
                ('pemakaian_virgin', models.PositiveIntegerField(default=0, verbose_name='Usage Virgin')),
                ('pemakaian_regrind', models.PositiveIntegerField(default=0, verbose_name='Usage Regrind')),
                ('kebutuhan_material', models.IntegerField(blank=True, null=True, verbose_name='Kebutuhan Material')),
                ('shift', models.CharField(blank=True, max_length=7, null=True, verbose_name='Shift')),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='PIC')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.product', verbose_name='Product')),
            ],
        ),
    ]
