# Generated by Django 4.0.3 on 2022-04-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopperfilldata',
            name='jam_isi',
            field=models.TimeField(default='08:14', verbose_name='jam_isi'),
        ),
    ]
