# Generated by Django 4.0.3 on 2022-04-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_hopperfilldata_jam_isi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HopperFillData',
        ),
    ]
