# Generated by Django 4.0.3 on 2022-04-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_pic_hopperfilldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopperfilldata',
            name='material',
            field=models.CharField(max_length=100, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='hopperfilldata',
            name='part_name',
            field=models.CharField(max_length=100, verbose_name='part_name'),
        ),
    ]
