# Generated by Django 4.0.3 on 2022-04-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_hopperfilldata_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=20, verbose_name='part_id')),
                ('part_name', models.CharField(max_length=100, verbose_name='part_name')),
                ('material', models.CharField(max_length=100, verbose_name='material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cycle_time')),
                ('customer', models.CharField(max_length=25, verbose_name='customer')),
                ('part_weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='part_weight')),
                ('runner_weight', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='runner_weight')),
                ('cavity', models.PositiveIntegerField(verbose_name='cavity')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='material.productcore', verbose_name='product')),
            ],
        ),
        migrations.RemoveField(
            model_name='hopperfilldata',
            name='material',
        ),
        migrations.RemoveField(
            model_name='hopperfilldata',
            name='part_id',
        ),
        migrations.RemoveField(
            model_name='hopperfilldata',
            name='part_name',
        ),
        migrations.AlterField(
            model_name='hopperfilldata',
            name='pic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.pic', verbose_name='pic'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='hopperfilldata',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='material.productcore', verbose_name='product'),
        ),
    ]
