# Generated by Django 4.0.3 on 2022-04-20 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0011_alter_hopperfilldata_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopperfilldata',
            name='pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='pic'),
        ),
    ]
