# Generated by Django 4.0.3 on 2022-04-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_alter_hopperfilldata_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='part_id'),
        ),
    ]
