# Generated by Django 4.0.3 on 2022-04-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_alter_hopperfilldata_jam_isi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_id',
            field=models.CharField(max_length=20, verbose_name='Part ID'),
        ),
    ]
